### ISSUE TITLE
bad encoding in newer entries' theory files

### ISSUE THREAD

**Issue by stuebinm** [carlinmack/afp#3]
So I just stumbled over  this redesign, and I have to say, I like it a lot!

Unfortunately, newer entries appear to have broken encoding/templating in their theory files (e.g. [this one](https://afp.theoremproving.org/entries/multiset_ordering_npc/theories/#Multiset_Ordering_More)):

![image](https://user-images.githubusercontent.com/24882790/166340635-26ab52ed-dc20-479f-91d0-5e39f623f2b0.png)

There's a lone `ead>` under the header, and non-ascii characters in the theory seem to get "chunked" apart:

![image](https://user-images.githubusercontent.com/24882790/166340346-2bbcb3fd-3f9a-4e5d-9072-344f93c8ab74.png)

Some cursory poking around in the history of entries seems to show that this first happened for [Regular Tree Relations](https://afp.theoremproving.org/entries/regular_tree_relations/) & for every entry since, but not for any before. That entry got added in 0ca12c26432fc16aed14e6c744905cd65dcbdd2c, and there's a bunch of non-automatic commits just before it (aafb704694beb6843b82aa40a118ee5b640c248e through 177416603283cd096fa22ce8995fdbd729c8ac5a) so I guess the bug got introduced somewhere in there, probably in [this diff](https://github.com/carlinmack/afp/commit/177416603283cd096fa22ce8995fdbd729c8ac5a#diff-aa09b3c807c8550945f2c641552f454ca2a0e5b50d13fe8ddb1da50ceea5811f)? 

… anyways, since I didn't get a python environment working to try and test this out further I'm just leaving this here as a bug report

**Comment by carlinmack** [comment]
I believe these errors are due to the upstream changes to the way theories are displayed in Isabelle2021-01 (see [*** Document preparation *** in that release](https://isabelle.in.tum.de/dist/Isabelle2021-1/doc/NEWS.html) for details) but many thanks for the bug report! This issue will be fixed in due course :)
